on:
  workflow_dispatch:
jobs:
  add-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: add date
        run: |
          date >> ./../../README.md
      - name: commit files
        run: |
          pwd
          git status
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md
          git commit -m 'update README.md'
          git push origin main