name: countup
on:
  workflow_dispatch:
jobs:
  add-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.UPDATE_README }}
      - name: count up
        working-directory: ./.github/workflows/scripts
        run: |
          cat count | awk '{print $1+1}' > tmpfile && mv tmpfile count
      - name: update readme
        run: |
          echo "$(cat ./.github/workflows/scripts/count) $(date)" >> README.md
      - name: commit files
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m 'count up'
          git push origin main